### ISSUE TITLE
Request for adding spectrum analyzer here.

### ISSUE THREAD

**Issue by rai4424** [OneOfEleven/uv-k5-firmware-custom#140]
Needs Spectrum analyzer here.
 Reasons:
1-  Egzumer customfile v.08 showing an issue.
2- Display tunrs blank during Tx.
3-Battery pesentage is  droping as   88%- 60%-30%-15%-06% at once and display starts glitching during transmission. 
4-Screen was totally white two times on 80% Battery when TXing  and Rx was working. I have nubers recordings but cant post here. This issue was not in versions below V0.5. 
So its my humble request to add spectrum analyzer in your file.

**Comment by lohtse** [comment]
Firstly it has been noted it is on the cards to add.. so leave it there


secondly I use egzumers daily and NEVER had the TX issue

thirdly   due to you supposed issue I have never had the battery issue

finally. devs ahev REAL LIFES AND ARE ALLOWED TO TAKE TIME OFF... SO be damn patientr and stop bloody pestering them...

**Comment by rai4424** [comment]
I have video proofs of this issue.
There was no any issue after installing old version.

**Comment by lohtse** [comment]
> I have video proofs of this issue. There was no any issue after installing old version.

Well I have custom dailys and NO ISSUE 


NOW STOP pestering the devs   and just friggin wait till they have time to respond  or just use an OLD verwsion that works for you..

Either way stop being a PITA

**Comment by rai4424** [comment]
@lohtse You are taking it personl.
I have requested to OneOfEleven plz.

**Comment by lohtse** [comment]
> @lohtse You are taking it personl. I have requested to OneOfEleven plz.

no I am just sick of people such as you pestering and when you don't get a response when you want it you pester further...  Its folks like you that get the issues section closed down  and devs leaving the k5 project... 


Just stop  simple

**Comment by bricky149** [comment]
IIRC the dev started to integrate the spectrum analyser and may be seen in app/spectrum.c.

As they work on this in their spare time, self-care is important to help keep the hobby fun. I would ask not to request features and to make an attempt to troubleshoot issues you find yourself so that maybe it can help others.

**Comment by rai4424** [comment]
Noted please
Thanks
