### ISSUE TITLE
menu on 2e880a6

### ISSUE THREAD

**Issue by IU4FIR** [OneOfEleven/uv-k5-firmware-custom#189]
### reporting some bugs with no priority  :-))
The key beep in some menu steps does not work, it is not always the same function, scrolling up and down the beep become silent in a random way. 
At menu step 45 of 61 a "1" symbol appears at the top right, I don't think it means anything.-->picture
**Nothing needs to be resolved, I'm just reporting for your information only.**

Best 73
![image](https://github.com/OneOfEleven/uv-k5-firmware-custom/assets/96939950/26835487-5b63-4c79-8b7e-adcc9088e4ce)

**Comment by ct1esj** [comment]
Yep, here I noticed the same thing

**Comment by OneOfEleven** [comment]
Thanks for letting me know.

I know about the random missing key beeps, been looking for the reason for it, I'll find it eventually.

The little '1' that appears is saying what the current sub menu number is, it also tells you in the CTCSS and CDCSS menus (if they are not set to 'off'). I'll make it so that the little number only shows up when you enter the sub menu.

**Comment by OneOfEleven** [comment]
I found where the missing beeps were going, have brought them back - hopefully.

**Comment by IU4FIR** [comment]
Great job, regarding the submenus I had thought of something similar but I hadn't analyzed it completely.
 I apologize for the incorrect reporting...
